import { Email } from "./types";

export const mockEmails: Email[] = [
  {
    id: 1,
    from: "provincial.office@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Monthly Report Submission",
    preview: "Please submit the monthly report by end of week...",
    body: "Dear Department Head,\n\nPlease be reminded to submit your department's monthly report by the end of this week. The report should include all relevant metrics and accomplishments.\n\nThank you for your cooperation.\n\nBest regards,\nProvincial Office",
    time: "2 hours ago",
    date: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isRead: false,
    isStarred: false,
    folder: "inbox",
    category: "Important",
  },
  {
    id: 2,
    from: "hr@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Staff Meeting Reminder",
    preview: "Reminder: Staff meeting scheduled for tomorrow...",
    body: "Hello Team,\n\nThis is a reminder that we have a staff meeting scheduled for tomorrow at 10:00 AM in the main conference room. Please come prepared with updates on your current projects.\n\nAgenda items will be sent separately.\n\nSee you there!\n\nHuman Resources",
    time: "5 hours ago",
    date: new Date(Date.now() - 5 * 60 * 60 * 1000),
    isRead: false,
    isStarred: true,
    folder: "inbox",
    category: "Meeting",
  },
  {
    id: 3,
    from: "finance@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Budget Approval Required",
    preview: "Your department budget request needs approval...",
    body: "Good day,\n\nYour department's budget request for Q2 2024 is pending approval. Please review the attached document and provide any additional information if needed.\n\nThe finance committee will review all submissions by Friday.\n\nThank you,\nFinance Department",
    time: "1 day ago",
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    isRead: false,
    isStarred: false,
    folder: "inbox",
    category: "Finance",
  },
  {
    id: 4,
    from: "it@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "System Maintenance Notice",
    preview: "Scheduled maintenance this weekend from 10 PM...",
    body: "Dear Users,\n\nPlease be informed that scheduled system maintenance will be conducted this weekend from 10:00 PM Saturday to 6:00 AM Sunday. During this time, the system will be unavailable.\n\nWe apologize for any inconvenience this may cause.\n\nIT Department",
    time: "2 days ago",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isRead: true,
    isStarred: false,
    folder: "inbox",
    category: "System",
  },
  {
    id: 5,
    from: "admin@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Policy Update",
    preview: "New office policies have been updated...",
    body: "All Staff,\n\nPlease be advised that new office policies have been updated and are now in effect. The updated policy manual is available on the intranet.\n\nKey changes include:\n- Updated leave policy\n- New remote work guidelines\n- Revised dress code\n\nPlease review and acknowledge receipt.\n\nAdministration",
    time: "3 days ago",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: true,
    isStarred: true,
    folder: "inbox",
    category: "Policy",
  },
  {
    id: 6,
    from: "legal@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Contract Review Request",
    preview: "Contract review needed for upcoming project...",
    body: "Dear Sir/Madam,\n\nWe need your department's review of the attached contract for the upcoming infrastructure project. Please provide feedback by next Monday.\n\nLegal Department",
    time: "4 days ago",
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    isRead: false,
    isStarred: false,
    folder: "inbox",
    category: "Legal",
  },
  {
    id: 7,
    from: "procurement@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Purchase Order Confirmation",
    preview: "Your purchase order has been confirmed...",
    body: "Good day,\n\nYour purchase order PO-2024-1234 has been confirmed and is being processed. Expected delivery date is within 5-7 business days.\n\nTracking information will be provided separately.\n\nProcurement Office",
    time: "5 days ago",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isRead: true,
    isStarred: false,
    folder: "inbox",
    category: "Procurement",
  },
  {
    id: 8,
    from: "planning@tarlac.gov.ph",
    to: "user@tarlac.gov.ph",
    subject: "Strategic Planning Session",
    preview: "Invitation to strategic planning session...",
    body: "Dear Department Head,\n\nYou are cordially invited to attend the strategic planning session scheduled for next month. Your input is valuable for setting our goals for the upcoming fiscal year.\n\nMore details to follow.\n\nPlanning Office",
    time: "1 week ago",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isRead: true,
    isStarred: false,
    folder: "inbox",
    category: "Planning",
  },
];

export const userEmail = "user@tarlac.gov.ph";

